create table Sensor (
    id int generated by default as identity primary key,
    name varchar(100) not null unique
);

create table Measurement (
    id int generated by default as identity primary key,
    value float not null,
    raining boolean not null,
    sensor_id int references  sensor(id) on delete  set null
)